### PR TITLE
20 world map game

### PR DESCRIPTION
**Pull request by stuar7**
Large amount of progress towards #19 and #20.

### CODE REVIEW

**Comment by stuar7** [comment]
This pull request now completes #28.

**Review by Ishi01 — APPROVED** [review]
Looks excellent, all functionality seems to work well, styling needs a bit of work but i'll self assign that and sort it out within the next day or so.

**Review by berry1104 — COMMENTED** [review]
all good, and seems need login required feature for game mode in next deliverable

**Review by berry1104 — APPROVED** [review]

**Review by cloud9ight — APPROVED** [review]
New world map question formats works well

**Pull request merged**
